# Generated by Django 4.1.2 on 2023-05-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futrest06app', '0004_alter_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(default='Sin apodo', max_length=30),
        ),
    ]
