# Generated by Django 4.1.2 on 2023-05-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futrest06app', '0005_player_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='Centrocampista', max_length=20),
        ),
    ]
