# Generated by Django 4.1.2 on 2023-05-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futrest06app', '0006_player_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint1', models.CharField(max_length=80)),
                ('hint2', models.CharField(max_length=80)),
                ('hint3', models.CharField(max_length=80)),
                ('hint4', models.CharField(max_length=80)),
                ('hint5', models.CharField(max_length=80)),
                ('solution', models.CharField(max_length=80)),
            ],
        ),
    ]
